app:
  name: messaging
  port: 8081
  env: dev #dev|stg|prod
  timezone: Asia/Jakarta
  debug: true  #in production set false
  read_timeout: 10 # in second
  write_timeout: 10 # in second
  callback_timeout: 10 # in second

api:
  prefix: "/devices/v1"

MariaDB:
  db_name: entraktest
  host: 172.17.0.2
  port: 3306
  user: root
  password: root
  charset: utf8

log:
  dir: "logs"
  filename: "devices.log"